// Assembles a listing's whole "content kit" into a single ZIP download:
// ready-to-post captions (tri-language, per platform), the branded graphic in
// three sizes, and the multi-slide carousel. Reuses the shared graphics lib so
// the bundled assets are identical to what's previewed on the page.
import { loadImage, renderGraphicCanvas, renderCarousel } from './graphics.js'
import { makeZip, canvasToBytes, textBytes } from './zip.js'
import { formatPrice, listingLabel } from './format.js'
import { listingPhotos } from './photos.js'
import { PLATFORM_MAP, LANGUAGES } from '../../shared/constants.js'

function slug(s) {
  return String(s || 'listing').replace(/[^\w]+/g, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'listing'
}

export async function buildKit({ listing, brand }) {
  const files = []
  const base = slug(listingLabel(listing))

  const loaded = await Promise.all([loadImage(brand.logo), ...listingPhotos(listing).slice(0, 4).map(loadImage)])
  const logo = loaded[0]
  const photos = loaded.slice(1)

  // Branded graphic — three sizes, high-res
  for (const fmt of ['square', 'portrait', 'story']) {
    const c = renderGraphicCanvas({ listing, brand, format: fmt, photo: photos[0] || null, logo })
    files.push({ name: `graphics/${base}-${fmt}.jpg`, data: await canvasToBytes(c, 'image/jpeg', 0.92) })
  }

  // Carousel slides, high-res
  const slides = renderCarousel({ listing, brand, photos, logo })
  for (let i = 0; i < slides.length; i++) {
    files.push({ name: `carousel/slide-${String(i + 1).padStart(2, '0')}.jpg`, data: await canvasToBytes(slides[i], 'image/jpeg', 0.92) })
  }

  // Captions — one file per platform, all three languages inside
  const content = listing.content || {}
  let captionCount = 0
  for (const pid of listing.platforms || []) {
    const platform = PLATFORM_MAP[pid]
    const perLang = content[pid]
    if (!platform || !perLang || !Object.keys(perLang).length) continue
    let txt = `${platform.name}\n${'='.repeat(platform.name.length)}\n\n`
    for (const lid of listing.languages) {
      const lang = LANGUAGES.find((l) => l.id === lid)
      const copy = perLang[lid]
      if (!lang || !copy) continue
      txt += `--- ${lang.native} ---\n${copy}\n\n`
    }
    files.push({ name: `captions/${slug(platform.short || platform.name)}.txt`, data: textBytes(txt) })
    captionCount++
  }

  const readme =
`SideKick — Content Kit
${listingLabel(listing)}
${formatPrice(listing.price, listing.listingType)}

This kit has everything you need to post this listing:

  captions/   Ready-to-post copy for each platform, in English, 中文 and
              Bahasa Malaysia. Each language is written natively — never
              machine-translated.
  graphics/   A branded image in three sizes:
                • square    — Feed / Facebook Marketplace
                • portrait  — Instagram feed
                • story     — Reels / WhatsApp Status
  carousel/   A multi-slide carousel for Instagram / Facebook.

Reel video: generate and download it from the listing page — it renders in
your browser on demand, so it isn't included here.

Nothing in this kit is auto-posted. You copy the caption, attach the image(s)
and post it yourself — that is exactly what keeps the accounts safe.

Generated by SideKick.
`
  files.push({ name: 'README.txt', data: textBytes(readme) })

  return { blob: makeZip(files), filename: `${base}-kit.zip`, files: files.length, captionCount, slides: slides.length }
}

export async function downloadKit(args) {
  const res = await buildKit(args)
  const url = URL.createObjectURL(res.blob)
  const a = document.createElement('a')
  a.href = url
  a.download = res.filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 5000)
  return res
}
